#jdbc.driverClassName=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#jdbc.username=root
#jdbc.password=123456
#scanPackage=com.example.spring.spring_tx

#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#  username: root
#  password: 123456

spring:
  redis:
    database: 0
    host: localhost
    password: 123456
    port: 6379

