spring:
  kafka:
    producer:
      acks: 1
      batch-size: 16384
      bootstrap-servers: 10.110.25.107:9092,10.10.6.6:9092,10.110.25.105:9092
      key-serializer: StringSerializer.class
      value-serializer: StringSerializer.class
      client-id: monitor-metric
logging:
  level: {root: info}